import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { SplashScreen, NavBar } from "../src/components/index";
import { Header } from "../src/sections/index";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative bg-slate-50 px-6">
        <div className="container mx-auto">
          <NavBar />
          <Header />
        </div>
        <SplashScreen />
      </div>
    </>
  );
};

export default Home;
