import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { SplashScreen } from "../src/components/index";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative">
        <div className="container mx-auto">
          <h1>Landing Page</h1>
        </div>
        <SplashScreen />
      </div>
    </>
  );
};

export default Home;
